---
- name: Verify
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: install a powertools package
      ansible.builtin.package:
        name: autotrace
        state: present
      notify:
        - remove a powertools package

  handlers:
    - name: remove a powertools package
      ansible.builtin.package:
        name: opencv
        state: absent
