---
#
# Ansible managed
#

name: Ansible Molecule

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '31 16 16 * *'

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: ansible-lint
        uses: ansible-community/ansible-lint-action@main
  test:
    needs:
      - lint
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        config:
          - namespace: robertdebock
            image: "enterpriselinux"
            tag: "8"
          - namespace: robertdebock
            image: "enterpriselinux"
            tag: "9"
          - namespace: library
            image: "rockylinux"
            tag: "8"
          - namespace: library
            image: "rockylinux"
            tag: "9"
          - namespace: library
            image: "almalinux"
            tag: "8"
          - namespace: library
            image: "almalinux"
            tag: "9"
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          path: "${{ github.repository }}"
      # - name: disable apparmor for mysql
      #   run: sudo ln -s /etc/apparmor.d/usr.sbin.mysqld /etc/apparmor.d/disable/
      # - name: parse apparmor for mysql
      #   run: sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.mysqld
      - name: molecule
        uses: robertdebock/molecule-action@6.0.1
        with:
          namespace: ${{ matrix.config.namespace }}
          image: ${{ matrix.config.image }}
          tag: ${{ matrix.config.tag }}
